### PR TITLE
Added version for regular C 

### PR DESCRIPTION
**Pull request by CharleySchaefer**

### CODE REVIEW

**Comment by lakshayg** [comment]
Thanks for the PR. I have been wanting to have C support for this too, however, I won't be able to access this PR in its current form since this has a lot of code duplication. Are you trying to include this in a project that is compiled using gcc?

**Comment by CharleySchaefer** [comment]
Hi,

Yes, I needed erfinv for a gcc compiler and I just adapted your code to
make it work for my own software. I know I didn’t create a neat version
without duplicate code, but in case my changes have any use to you I shared
it - no worries if you won’t find any need for it.
In any case, thanks for sharing your code, it’s very useful.

Best wishes,
Charley

Op vr 3 jul. 2020 om 08:04 schreef Lakshay Garg <notifications@github.com>

**Comment by lakshayg** [comment]
I have converted the erfinv code to work with both C and C++

**Comment by CharleySchaefer** [comment]
This is great, many thanks!

Op zo 5 jul. 2020 om 07:50 schreef Lakshay Garg <notifications@github.com>:

**Pull request closed without merging**
